spring:
  datasource:
    username: ${spring.datasource.username}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
  application:
    name: companies-crud
  profiles:
    default: default
  config:
    import:
      "optional:configserver:http://localhost:7777"
server:
  servlet:
    context-path: /companies-crud
  port: 8081
#  port: 0
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/