spring:
  application:
    name: gateway
  profiles:
#    default: eureka-off
    default: eureka-on
server:
  port: 4040

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
#    fetch-registry: false